# Generated by Django 4.0.4 on 2022-05-17 01:53

from django.db import migrations, models
import django.db.models.deletion
import eld_admin.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=56)),
                ('city', models.CharField(max_length=35)),
                ('zip', models.CharField(max_length=10, validators=[eld_admin.validators.validate_zip_code])),
                ('street', models.CharField(max_length=35)),
                ('building', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('eld_enabled', models.BooleanField()),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('home_terminal_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eld_admin.address')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('optional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[eld_admin.validators.validate_unit_year])),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('license_plate_no', models.CharField(max_length=20)),
                ('VIN', models.CharField(max_length=17, unique=True, validators=[eld_admin.validators.validate_VIN])),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eld_admin.unit')),
            ],
            bases=('eld_admin.unit',),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eld_admin.unit')),
            ],
            bases=('eld_admin.unit',),
        ),
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='eld_admin.unitgroup'),
        ),
        migrations.AddField(
            model_name='unit',
            name='license_plate_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eld_admin.province'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('from_city', models.CharField(max_length=35)),
                ('to_city', models.CharField(max_length=35)),
                ('distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_docs_uploaded', models.BooleanField(default=False)),
                ('DVIR_completed', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='eld_admin.driver')),
                ('from_province', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='from_province', to='eld_admin.province')),
                ('to_province', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_province', to='eld_admin.province')),
                ('trailers', models.ManyToManyField(blank=True, null=True, to='eld_admin.trailer')),
                ('trucks', models.ManyToManyField(blank=True, null=True, to='eld_admin.truck')),
            ],
            options={
                'unique_together': {('date', 'driver')},
            },
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eld_admin.province'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('license_plate_no', 'license_plate_state')},
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('odometer_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(max_length=40)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eld_admin.log')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eld_admin.status')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eld_admin.truck')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eld_admin.trailer'),
        ),
        migrations.AddField(
            model_name='driver',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eld_admin.truck'),
        ),
    ]
