# Generated by Django 4.0.4 on 2022-05-16 20:16

from django.db import migrations, models
import django.db.models.deletion
import eld_admin.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('eld_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logprofile',
            name='truck',
            field=models.ManyToManyField(to='eld_admin.truck'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eld_admin.trailer'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eld_admin.truck'),
        ),
        migrations.AlterField(
            model_name='logevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logevent',
            name='odometer_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logprofile',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logprofile',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='eld_admin.unitgroup'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='license_plate_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[eld_admin.validators.validate_unit_year]),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('license_plate_no', 'license_plate_state')},
        ),
    ]
