# Generated by Django 4.0.4 on 2022-05-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eld_admin', '0002_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='from_city',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='from_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='from_province', to='eld_admin.province'),
        ),
        migrations.AlterField(
            model_name='log',
            name='to_city',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='to_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_province', to='eld_admin.province'),
        ),
    ]
