# Generated by Django 4.0.4 on 2022-05-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eld_admin', '0002_logprofile_truck_alter_driver_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='eld_admin.driver'),
        ),
        migrations.AddField(
            model_name='log',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='trailers',
            field=models.ManyToManyField(to='eld_admin.trailer'),
        ),
        migrations.AddField(
            model_name='log',
            name='trucks',
            field=models.ManyToManyField(to='eld_admin.truck'),
        ),
        migrations.DeleteModel(
            name='LogProfile',
        ),
    ]
