# Generated by Django 4.0.4 on 2022-05-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eld_admin', '0003_log_distance_log_driver_log_notes_log_trailers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('date', 'driver')},
        ),
    ]
