# Generated by Django 4.0.4 on 2022-05-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eld_admin', '0003_alter_log_from_city_alter_log_from_province_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='license_plate_state',
            new_name='license_plate_province',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('license_plate_no', 'license_plate_province')},
        ),
    ]
