# Generated by Django 4.0.4 on 2022-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_admin', '0004_alter_log_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
