# Generated by Django 4.0.4 on 2022-05-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_admin', '0005_alter_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='DVIR_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='shipping_docs_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='trailers',
            field=models.ManyToManyField(blank=True, null=True, to='eld_admin.trailer'),
        ),
        migrations.AlterField(
            model_name='log',
            name='trucks',
            field=models.ManyToManyField(blank=True, null=True, to='eld_admin.truck'),
        ),
        migrations.AlterField(
            model_name='logevent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitgroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
